-- MARAHIL seed data
-- Run after schema.sql

- chapters
insert into chapters (key,number,chapter,prayer,color_name,color_hex,sort_order) values ('bad','01','Bad’','Fajr','Soft Gold','#D4AF37',01);
insert into chapters (key,number,chapter,prayer,color_name,color_hex,sort_order) values ('ishraq','02','Ishraq','Sunrise','Bright Gold','#EBC94A',02);
insert into chapters (key,number,chapter,prayer,color_name,color_hex,sort_order) values ('zuhr','03','Zuhr','Dhuhr','Warm Gold','#C99A3E',03);
insert into chapters (key,number,chapter,prayer,color_name,color_hex,sort_order) values ('athar','04','Athar','Asr','Rose Gold','#B76E79',04);
insert into chapters (key,number,chapter,prayer,color_name,color_hex,sort_order) values ('wasl','05','Wasl','Maghrib','Ember','#A0522D',05);
insert into chapters (key,number,chapter,prayer,color_name,color_hex,sort_order) values ('layl','06','Layl','Isha','Black Gold','#3C3A36',06);

- products
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-FAHL Bad’','marahil-al-fahl-bad','fahl','fragrance','bad','بد','Fajr','Soft Gold','#D4AF37','The first chapter. A fresh start at the first light of day.','Fresh start',ARRAY['Fresh Citrus','Oud','White Musk']::text[],ARRAY['Fresh Citrus']::text[],ARRAY['Oud']::text[],ARRAY['White Musk']::text[],125,185,NULL,NULL,NULL,'MRH-F-BAD-50','MRH-F-BAD-100',NULL,true,false,1);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-FAHL Ishraq','marahil-al-fahl-ishraq','fahl','fragrance','ishraq','إشراق','Sunrise','Bright Gold','#EBC94A','The second chapter. Energy rising with the morning sun.','Energy',ARRAY['Saffron','Black Pepper','Amber']::text[],ARRAY['Saffron']::text[],ARRAY['Black Pepper']::text[],ARRAY['Amber']::text[],125,185,NULL,NULL,NULL,'MRH-F-ISH-50','MRH-F-ISH-100',NULL,true,false,2);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-FAHL Zuhr','marahil-al-fahl-zuhr','fahl','fragrance','zuhr','ظهر','Dhuhr','Warm Gold','#C99A3E','The third chapter. The warmth of noon.','Noon',ARRAY['Warm Cardamom','Amber']::text[],ARRAY['Warm Cardamom']::text[],ARRAY[]::text[],ARRAY['Amber']::text[],125,185,NULL,NULL,NULL,'MRH-F-ZUH-50','MRH-F-ZUH-100',NULL,true,false,3);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-FAHL Athar','marahil-al-fahl-athar','fahl','fragrance','athar','أثر','Asr','Rose Gold','#B76E79','The fourth chapter. The lingering trace of the afternoon.','Afternoon',ARRAY['Rose','Oud','Leather']::text[],ARRAY['Rose']::text[],ARRAY['Oud']::text[],ARRAY['Leather']::text[],125,185,NULL,NULL,NULL,'MRH-F-ATH-50','MRH-F-ATH-100',NULL,true,false,4);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-FAHL Wasl','marahil-al-fahl-wasl','fahl','fragrance','wasl','وصل','Maghrib','Ember','#A0522D','The fifth chapter. Union at the hour of sunset.','Union',ARRAY['Leather','Ember','Oud']::text[],ARRAY['Leather']::text[],ARRAY['Ember']::text[],ARRAY['Oud']::text[],125,185,NULL,NULL,NULL,'MRH-F-WAS-50','MRH-F-WAS-100',NULL,true,false,5);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-FAHL Layl','marahil-al-fahl-layl','fahl','fragrance','layl','ليل','Isha','Black Gold','#3C3A36','The sixth chapter. The depth of night.','Night',ARRAY['Dark Oud','Vanilla','Amber']::text[],ARRAY['Dark Oud']::text[],ARRAY['Vanilla']::text[],ARRAY['Amber']::text[],125,185,NULL,NULL,NULL,'MRH-F-LAY-50','MRH-F-LAY-100',NULL,true,false,6);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL Discovery','marahil-discovery-fahl','fahl','discovery',NULL,'اكتشاف',NULL,NULL,NULL,'Four 10ml chapters. The complete ritual, gathered. Begin your collection.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,85,'4 × 10ml',85,'MRH-DISC-40',NULL,NULL,true,false,7);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Onyx Heavy Bead 12mm','onyx-heavy-bead-12mm','fahl','jewelry',NULL,'خرزة العقيق',NULL,NULL,NULL,'Heavy onyx bead, 12mm. Black. Worn with the chapter it keeps.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,95,NULL,NULL,'MRH-J-M-BEAD-B12',NULL,NULL,true,false,8);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Cuff Heiba Gold','cuff-heiba-gold-fahl','fahl','jewelry',NULL,'سوار الهيبة',NULL,NULL,NULL,'Heiba wide cuff in gold. مراحل الفحل. A presence on the wrist.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,245,NULL,NULL,'MRH-J-M-CUFF-G',NULL,NULL,true,false,9);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Ring Aqeeq Black Gold','ring-aqeeq-black-gold','fahl','jewelry',NULL,'خاتم العقيق',NULL,NULL,NULL,'Aqeeq ring, black stone set in gold. A signature of the house.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,175,NULL,NULL,'MRH-J-M-RING-B',NULL,NULL,true,false,10);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Pendant Square','pendant-square-fahl','fahl','jewelry',NULL,'قلادة مربعة',NULL,NULL,NULL,'Square pendant, مراحل الفحل. Gold, restrained, architectural.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,195,NULL,NULL,'MRH-J-M-PEND-SQ',NULL,NULL,true,false,11);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Gift Box Brotherhood','gift-box-brotherhood','fahl','gift',NULL,'صندوق الأخوة',NULL,NULL,NULL,'Matte black box, gold details. Choose a chapter, with bracelet and ring. A complete ritual, given.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,395,NULL,NULL,'MRH-SET-BRO-01',NULL,NULL,true,true,12);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-ANIQA Bad’','marahil-al-aniqa-bad','aniqa','fragrance','bad','بد','Fajr','Soft Gold','#D4AF37','The first chapter. A soft first light, white musk and rose.','Fresh start',ARRAY['White Musk','Rose']::text[],ARRAY['White Musk']::text[],ARRAY['Rose']::text[],ARRAY[]::text[],125,185,NULL,NULL,NULL,'MRH-A-BAD-50','MRH-A-BAD-100',NULL,true,false,1);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-ANIQA Ishraq','marahil-al-aniqa-ishraq','aniqa','fragrance','ishraq','إشراق','Sunrise','Bright Gold','#EBC94A','The second chapter. Luminous saffron and rose at sunrise.','Energy',ARRAY['Saffron','Rose','Luminous']::text[],ARRAY['Saffron']::text[],ARRAY['Rose']::text[],ARRAY['Luminous']::text[],125,185,NULL,NULL,NULL,'MRH-A-ISH-50','MRH-A-ISH-100',NULL,true,false,2);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-ANIQA Zuhr','marahil-al-aniqa-zuhr','aniqa','fragrance','zuhr','ظهر','Dhuhr','Warm Gold','#C99A3E','The third chapter. Warm vanilla and soft oud at noon.','Noon',ARRAY['Warm Vanilla','Soft Oud']::text[],ARRAY['Warm Vanilla']::text[],ARRAY['Soft Oud']::text[],ARRAY[]::text[],125,185,NULL,NULL,NULL,'MRH-A-ZUH-50','MRH-A-ZUH-100',NULL,true,false,3);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-ANIQA Athar','marahil-al-aniqa-athar','aniqa','fragrance','athar','أثر','Asr','Rose Gold','#B76E79','The fourth chapter. Rose and gold oud, ward of the afternoon.','Afternoon',ARRAY['Rose','Gold Oud','Ward']::text[],ARRAY['Rose']::text[],ARRAY['Gold Oud']::text[],ARRAY['Ward']::text[],125,185,NULL,NULL,NULL,'MRH-A-ATH-50','MRH-A-ATH-100',NULL,true,false,4);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-ANIQA Wasl','marahil-al-aniqa-wasl','aniqa','fragrance','wasl','وصل','Maghrib','Ember','#A0522D','The fifth chapter. Amber and ward at the hour of union.','Union',ARRAY['Amber','Ward']::text[],ARRAY['Amber']::text[],ARRAY['Ward']::text[],ARRAY[]::text[],125,185,NULL,NULL,NULL,'MRH-A-WAS-50','MRH-A-WAS-100',NULL,true,false,5);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL AL-ANIQA Layl','marahil-al-aniqa-layl','aniqa','fragrance','layl','ليل','Isha','Black Gold','#3C3A36','The sixth chapter. Dark musk, pearl and amber through the night.','Night',ARRAY['Dark Musk','Pearl','Amber']::text[],ARRAY['Dark Musk']::text[],ARRAY['Pearl']::text[],ARRAY['Amber']::text[],125,185,NULL,NULL,NULL,'MRH-A-LAY-50','MRH-A-LAY-100',NULL,true,false,6);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('MARAHIL Discovery','marahil-discovery-aniqa','aniqa','discovery',NULL,'اكتشاف',NULL,NULL,NULL,'Four 10ml chapters. The complete ritual, gathered. Begin your collection.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,85,'4 × 10ml',85,'MRH-A-DISC-40',NULL,NULL,true,false,7);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Onyx Rose Bead','onyx-rose-bead','aniqa','jewelry',NULL,'خرزة الورد',NULL,NULL,NULL,'Onyx rose bead. A quiet ornament worn with the chapter it keeps.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,95,NULL,NULL,'MRH-J-A-BEAD-R',NULL,NULL,true,false,8);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Cuff Anaqa Rose Gold','cuff-anaqa-rose-gold','aniqa','jewelry',NULL,'سوار الأنيقة',NULL,NULL,NULL,'Anaqa cuff in rose gold. مراحل الأنيقة. Soft strength on the wrist.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,245,NULL,NULL,'MRH-J-A-CUFF-RG',NULL,NULL,true,false,9);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Ring Pearl Aqeeq','ring-pearl-aqeeq','aniqa','jewelry',NULL,'خاتم اللؤلؤ',NULL,NULL,NULL,'Pearl aqeeq ring. A signature of the house, in soft light.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,175,NULL,NULL,'MRH-J-A-RING-P',NULL,NULL,true,false,10);
insert into products (name,slug,branch,category,chapter,arabic_name,prayer,color_name,color_hex,description,meaning,juice_notes,top_notes,heart_notes,base_notes,price_50,price_100,price,discovery_size,discovery_price,sku,sku_100,image_url,is_active,is_memorial_edition,sort_order) values ('Gift Box Elegance','gift-box-elegance','aniqa','gift',NULL,'صندوق الأناقة',NULL,NULL,NULL,'Cream box, rose-gold details. Choose a chapter, with bracelet and ring. A complete ritual, given.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,395,NULL,NULL,'MRH-SET-ANA-01',NULL,NULL,true,true,11);
